import grpc
import logging
import os
import sys
import time
from concurrent import futures
from typing import Optional

# Ensure backend and root directories are in path for generated modules and ag_proxy
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Generated gRPC code (will be generated by grpc_tools.protoc)
import messaging_pb2
import messaging_pb2_grpc

from routes_verify import verify_prompt as rest_verify_prompt
from routes_verify import PromptVerifyRequest

log = logging.getLogger("grpc_server")

class PromptServiceServicer(messaging_pb2_grpc.PromptServiceServicer):
    """
    gRPC implementation of the PromptService.
    Calls the same verification logic used by the REST API.
    """

    async def SendPrompt(self, request, context):
        log.info(f"gRPC request received: prompt='{request.prompt[:50]}...' intent='{request.intent}'")
        
        # Build a pseudo-request for our existing REST logic
        verify_req = PromptVerifyRequest(
            prompt=request.prompt,
            agent_id="grpc-friend-agent",
            source="direct"
        )
        
        try:
            # Note: verify_prompt is async, so we need to handle it properly
            # In a real gRPC server with asyncio support, we'd use grpc.aio
            from ag_proxy.proxy import inspect_body
            response = await rest_verify_prompt(verify_req)
            is_approved = response.get("verdict") == "ALLOW"
            
            # Map findings to a comma-separated string for "detected"
            findings = response.get("findings", [])
            detected_list = []
            for f in findings:
                if isinstance(f, dict):
                    detected_list.append(f.get("description", f.get("layer", "unknown")))
                else:
                    detected_list.append(str(f))
            
            detected_str = ", ".join(detected_list) if not is_approved else ""
            authorized_str = request.intent if is_approved else "none"

            return messaging_pb2.PromptResponse(
                approved=is_approved,
                authorized=authorized_str,
                detected=detected_str
            )
        except Exception as e:
            log.error(f"Error processing gRPC request: {e}")
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(f"Internal error: {e}")
            return messaging_pb2.PromptResponse(approved=False)

def serve():
    port = os.environ.get("AGENTGUARD_GRPC_PORT", "50051")
    server = grpc.aio.server()
    messaging_pb2_grpc.add_PromptServiceServicer_to_server(PromptServiceServicer(), server)
    
    server_address = f'[::]:{port}'
    
    # TLS Configuration
    CERT_PATH = "/app/certs/server.cert"
    if not os.path.exists(CERT_PATH):
        CERT_PATH = "/app/certs/server.crt"
        
    KEY_PATH  = "/app/certs/server.key"
    
    if os.path.exists(CERT_PATH) and os.path.exists(KEY_PATH):
        server_credentials = grpc.ssl_server_credentials(
            [(open(KEY_PATH, 'rb').read(), open(CERT_PATH, 'rb').read())]
        )
        server.add_secure_port(server_address, server_credentials)
        log.info(f"gRPC server starting WITH TLS on port {port}")
    else:
        server.add_insecure_port(server_address)
        log.warning(f"gRPC server starting INSECURE (certs missing) on port {port}")
        log.warning(f"Please place certs in {CERT_PATH} and {KEY_PATH}")

    return server, server_address

async def run_grpc_server():
    server, addr = serve()
    await server.start()
    log.info(f"gRPC server listening on {addr}")
    await server.wait_for_termination()

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    import asyncio
    asyncio.run(run_grpc_server())
