# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/messaging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backend/messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x61\x63kend/messaging.proto\x12\tmessaging\"/\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\"H\n\x0ePromptResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x12\n\nauthorized\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65tected\x18\x03 \x01(\t2R\n\rPromptService\x12\x41\n\nSendPrompt\x12\x18.messaging.PromptRequest\x1a\x19.messaging.PromptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMPTREQUEST']._serialized_start=38
  _globals['_PROMPTREQUEST']._serialized_end=85
  _globals['_PROMPTRESPONSE']._serialized_start=87
  _globals['_PROMPTRESPONSE']._serialized_end=159
  _globals['_PROMPTSERVICE']._serialized_start=161
  _globals['_PROMPTSERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
