foreground = yes
debug = 5
pid =

[sentinel-gateway]
accept  = 3005
connect = 127.0.0.1:3000
cert    = /Users/uddalakmukhopadhyay/Developer/Web Development Projects/The-Third-Reich/backend/services/infra/stunnel/stunnel.pem
sslVersion = TLSv1.2
ciphers = ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
renegotiation = no
